plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
	id 'eclipse'
	id 'idea'
}

version = project.mod_version
group = project.maven_group

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
}

loom {
	mods {
		"whereismystuff" {
			sourceSet sourceSets.main
		}
	}
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

	// Fabric API. This is technically optional, but you probably want it anyway.
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

}

processResources {
	def version = project.version
	inputs.property "version", version

	filesMatching("fabric.mod.json") {
		expand "version": version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = Integer.parseInt(project.java_version)
}

java {
	// Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
	// if it is present.
	// If you remove this line, sources will not be generated.
	withSourcesJar()

	sourceCompatibility = JavaVersion.toVersion(project.java_version)
	targetCompatibility = JavaVersion.toVersion(project.java_version)
}

jar {
	def projectName = project.name
	inputs.property "projectName", projectName

	from("LICENSE") {
		rename { "${it}_$projectName"}
	}
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

tasks.named('remapJar') {
	doLast {
		def jarFile = archiveFile.get().asFile
		def userHome = System.getProperty("user.home")
		def destDirs = [
			"${userHome}/Library/Application Support/ModrinthApp/profiles/ModDeneme/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/Mod deneme 1.21.11/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/1.21.10/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/1.21.9/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/1.21.8/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/1.21.7/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/1.21.6/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/1.21.5/mods/",
			"${userHome}/Library/Application Support/ModrinthApp/profiles/1.21/mods/"
		]
		destDirs.each { dirPath ->
			def destDir = file(dirPath)
			if (destDir.exists()) {
				copy {
					from jarFile
					into destDir
				}
				println "[WIMS-Build] Automatically copied compiled jar to: ${dirPath}"
			} else {
				println "[WIMS-Build] Skipping non-existent Modrinth directory: ${dirPath}"
			}
		}
	}
}

fabricApi {
	configureTests {
		createSourceSet = true
		modId = "whereismystuff-test"
		enableGameTests = (project.minecraft_version == "1.21.4")
		enableClientGameTests = (project.minecraft_version == "1.21.4")
		eula = true
	}
}

project.afterEvaluate {
	if (tasks.findByName('compileGametestJava') != null && project.minecraft_version != "1.21.4") {
		tasks.named('compileGametestJava') {
			exclude "**/*.java"
		}
	}
}

eclipse {
	classpath {
		plusConfigurations += [configurations.gametestCompileClasspath]
	}
}

idea {
	module {
		testSources.from(sourceSets.gametest.java.srcDirs)
	}
}


